config/routes.rb
Project96821::Application.routes.draw do
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/profile' => 'devise/registrations#edit'
  end

  resources :snippets do
    resources :comments
  end

  root :to => 'snippets#new'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :snippet_id, :linenum, :user_id, :time
  validates :content, :presence => true, :length => { :maximum => 5000 }
  belongs_to :user
end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  attr_accessible :content, :desc, :filetype, :name, :time, :user_id, :commentable
  has_many :comments
  belongs_to :user
  validates :name, :presence => true, :length => { :maximum => 50 }
  validates :desc, :length => { :maximum => 10000 }
  validates :content, :presence => true, :length => { :maximum => 10000000 }
  validates :filetype, :numericality => { :only_integer => true }

end

app/models/user.rb
require 'digest/md5'

class User < ActiveRecord::Base
  before_save :set_avatar

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation,
    :remember_me, :avatar
  # attr_accessor :avatar
  # attr_accessible :title, :body

  has_many :snippets
  validates :name, :presence => true
  # has_many :comments

protected
  def set_avatar
    self.avatar = Digest::MD5.hexdigest(self.email.downcase)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :get_snippet
  before_filter :authenticate_user!, :only => [:create, :destroy]
  respond_to :json

  # GET /comments.json
  def index
    @comments = @snippet.comments.order('linenum ASC')
    respond_to do |format|
      format.json { render json: @comments.to_json(:include => :user) }
    end
  end

  # POST /comments.json
  def create
    @comment = @snippet.comments.build(params[:comment])

    respond_to do |format|
      if @comment.save
        # format.json { render json: @comment, status: :ok, location: @comment }
        format.json { render json: @comment.to_json(:include => :user), status: :ok }
      else
        # format.json { render json: @comment.errors, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1.json
  def destroy
    @comment = @snippet.comments.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.json { head :no_content }
    end
  end

private
  def get_snippet
    @snippet = Snippet.find params[:snippet_id]
  end
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  before_filter :typenames, only: [:index, :show]
  before_filter :authenticate_user!, :only => [:edit, :update, :destroy]

  def typenames
    @types = ['', 'html', 'css', 'js', 'rb', 'c', 'java', 'py', 'xml']
    @typenames = ['Text', 'HTML', 'CSS', 'JavaScript', 'Ruby', 'C/C++',
      'Java', 'Python', 'XML']
  end

  def index
    @snippets = Snippet.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @snippets }
      format.xml { render xml: @snippets }
    end
  end

  def show
    @snippet = Snippet.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @snippet }
      format.xml { render xml: @snippet }
    end
  end

  def new
    @snippet = Snippet.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @snippet }
      format.xml { render xml: @snippet }
    end
  end

  def edit
    @snippet = Snippet.find(params[:id])
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @snippet }
      format.xml { render xml: @snippet }
    end
  end

  def create
    @snippet = Snippet.new(params[:snippet])
    respond_to do |format|
      if @snippet.save
        format.html { redirect_to @snippet, notice: 'Snippet was successfully created.' }
        format.json { render json: @snippet, status: :created, location: @snippet }
        format.xml { render xml: @snippet, status: :created, location: @snippet }
      else
        # format.html { render action: "new" }
        format.html { redirect_to :root, notice: 'An error has occurred.' }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
        format.xml { render xml: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @snippet = Snippet.find(params[:id])
    respond_to do |format|
      if @snippet.update_attributes(params[:snippet])
        format.html { redirect_to @snippet, notice: 'Snippet was successfully updated.' }
        format.json { head :no_content }
        format.xml { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
        format.xml { render xml: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @snippet = Snippet.find(params[:id])
    @snippet.destroy
    respond_to do |format|
      format.html { redirect_to snippets_url }
      format.json { render json: {redirect_url: snippets_url}, status: :ok }
      format.xml { render xml: {redirect_url: snippets_url}, status: :ok }
    end
  end
end

app/helpers/application_helper.rb
require 'digest/md5'

module ApplicationHelper
  def page_title(title)
    base = 'EarlGrey'
    if title.empty?
      base
    else
      "#{base} - #{title}"
    end
  end

  def load_js(filenames)
    if filenames.empty?
      # do nothing
    else
      tags = ''
      filenames.each do |f|
        tags << javascript_include_tag(f)
      end
      tags
    end
  end

  def calc_hash(email)
    if (not email.empty?)
      Digest::MD5.hexdigest(email.downcase)
    else
      ""
    end
  end
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title><%= page_title(yield :title) %></title>
    <!--link rel="shortcut icon" href="../assets/ico/favicon.ico"-->
    <%= stylesheet_link_tag "bootstrap", :media => "all" %>
    <%= stylesheet_link_tag "style", :media => "all" %>
    <%= javascript_include_tag "prettify" %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <header class="header">
      <div class="container">
        <h1 class="pull-left"><%= link_to 'EarlGrey', root_path %></h1>
        <div class="user">
          <div class="user-actions navbar-inverse pull-right">
            <% if user_signed_in? %>
              <div class="user-img pull-left">
                <a id="u-gravatar" href="http://gravatar.com/" title="Go to Gravatar.com and change your profile image" rel="tooltip" data-placement="bottom" target="_blank"><img src="http://gravatar.com/avatar/<%= current_user.avatar %>?s=32" alt=""></a>
              </div>
              <ul class="nav nav-pills pull-left">
                <li><span id="u-name" class="user-name"><%= current_user.name %></span></li>
                <li><a id="u-profile" href="<%= edit_user_registration_path %>" title="My Profile">Profile</a></li>
                <li><a id="u-signout" href="<%= destroy_user_session_path %>" title="Sign Out">Sign Out</a></li>
              </ul>
            <% else %>
              <ul class="nav nav-pills pull-left">
                <li>
                <a id="u-login" href="<%= new_user_session_path %>" title="Log In">Log In</a>
                </li>
                <li><a id="u-signup" href="<%= new_user_registration_path %>" title="Sign Up">Sign Up</a></li>
              </ul>
            <% end %>
          </div>
        </div>
      </div>
    </header>

    <div class="container">
      <%= yield %>
    </div>

    <footer class="footer">
      <div class="container">
        <p><strong>EarlGrey</strong> - A product of team Maccha. | Made by Yang Piao (yp {at} cmu.edu)</p>
        <p>This is the individual project of 96-821. The source code is on 
        <a href="https://github.com/yangpiao/96821-project" title="GitHub Page">GitHub</a>.
        </p>
      </div>
    </footer>

    <div id="tipDlg" class="modal hide fade">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 id="tipDlg-hd">Header</h3>
      </div>
      <div id="tipDlg-bd" class="modal-body"></div>
      <div class="modal-footer">
        <a href="#" id="tipDlg-c" class="btn" data-dismiss="modal" aria-hidden="true">Cancel</a>
        <a href="#" id="tipDlg-s" class="btn btn-primary">OK</a>
      </div>
    </div>

    <div id="loginDlg" class="user-dlg modal hide fade">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Log In</h3>
      </div>
      <%= form_for("user", :url => user_session_path, :html => { :class => "login-form" }) do |f| %>
      <div class="modal-body">
        <%= f.label :email do %>
          Email<span id="login-email-err" class="error"></span>
        <% end %>
        <%= f.email_field :email, :class => "input-xlarge" %>
        <%= f.label :password do %>
          Password<span id="login-pass-err" class="error"></span>
        <% end %>
        <%= f.password_field :password, :class => "input-xlarge" %>
        <%= f.label :remember_me, :class => "checkbox" do %>
          <%= f.check_box :remember_me %> Remember me
        <% end %>
      </div>
      <div class="modal-footer login-actions">
        <%= f.submit "Log In", :class => "btn btn-primary", :id => "user-login" %>
        <%= link_to "Forgot password?", new_password_path('user'), :class => "forgot-pass" %>
      </div>
      <% end %>
    </div>

    <div id="signupDlg" class="user-dlg modal hide fade">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Sign Up</h3>
      </div>
      <%= form_for("user", :url => user_registration_path, :html => { :class => "login-form" }) do |f| %>
      <div class="modal-body">
        <%= f.label :name do %>
          Name<span id="signup-name-err" class="error"></span>
        <% end %>
        <%= f.text_field :name, :class => "input-xlarge" %>
        <label for="user_email_s">
          Email<span id="signup-email-err" class="error"></span>
        </label>
        <input class="input-xlarge" id="user_email_s" name="user[email]" size="30" type="email">
        <label for="user_password_s">
          Password<span id="signup-pass-err" class="error"></span>
        </label>
        <input class="input-xlarge" id="user_password_s" name="user[password]" size="30" type="password">
        <%= f.label :password_confirmation do %>
          Confirm Password<span id="signup-pass-c-err" class="error"></span>
        <% end %>
        <%= f.password_field :password_confirmation, :class => "input-xlarge" %>
      </div>
      <div class="modal-footer login-actions">
        <%= f.submit "Sign Up", :class => "btn btn-primary", :id => "user-signup" %>
      </div>
      <% end %>
    </div>

    <script>var gEarlGreyUser = <%= raw current_user.to_json %></script>
    <%= javascript_include_tag "jquery" %>
    <%= javascript_include_tag "bootstrap" %>
    <%= javascript_include_tag "snippet.base" %>
    <% if not (yield :jsfile).empty? %>
    <%= javascript_include_tag(yield :jsfile) %>
    <% end %>

    <!--[if IE]>
    <script>
      var dlg = gEarlGreyCommon.dlg;
      dlg.set({
        hd: 'Oops...',
        bd: 'This website currently does not support Internet Explorer. Please use latest Chrome/Firefox/Safari/Opera to make web browsing faster, safer and easier.',
        hideOk: true,
        hideCancel: true,
        hideClose: true
      });
      dlg.show();
    </script>
    <![endif]-->

    <!--[if lt IE 8]>
    <script>
    /*if (!(window.ActiveXObject && document.documentMode)) {
      var dlg = gEarlGreyCommon.dlg;
      dlg.set({
        hd: 'Oops...',
        bd: 'You are using a really old browser, so the page will not be rendered properly. Please upgrade to Internet Explorer 8 or higher, or use latest Chrome/Firefox/Safari/Opera, to make web browsing faster, safer and easier.',
        hideOk: true,
        hideCancel: true,
        hideClose: true
      });
      dlg.show();
    }*/
    </script>
    <![endif]-->
  </body>
</html>

app/views/snippets/_form.html.erb
<div class="snippet-form content">
  <p class="form-legend alert alert-info">
    <strong>EarlGrey</strong> is a tool to share code with others, 
    and to see comments on your code.
  </p>
  <div class="form-body content-box">
    <%= form_for(@snippet, :html => {:class => ''}) do |f| %>
      <div class="clearfix">
        <div class="form-name">
          <h4>Name<span id="name-error" class="notice"></span></h4>
          <%= f.text_field :name, :size => 20, :class => '', :placeholder => 'Snippet Name' %>
        </div>
        <div class="form-filetype btn-toolbar">
          <h4>Type</h4>
          <div class="btn-group">
            <a href="#" class="type btn" data-value="0" id="default-type">Text</a>
            <a href="#" class="type btn" data-value="1">HTML</a>
            <a href="#" class="type btn" data-value="2">CSS</a>
            <a href="#" class="type btn" data-value="3">JavaScript</a>
            <a href="#" class="type btn" data-value="4">Ruby</a>
          </div>
          <div class="btn-group">
            <a class="more-btn btn dropdown-toggle" data-toggle="dropdown" href="#"><em>More </em><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a class="type-more" tabindex="-1" href="#" data-value="5">C/C++</a></li>
              <li><a class="type-more" tabindex="-1" href="#" data-value="6">Java</a></li>
              <li><a class="type-more" tabindex="-1" href="#" data-value="7">Python</a></li>
              <li><a class="type-more" tabindex="-1" href="#" data-value="8">XML</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="form-desc">
        <h4>Description<span id="desc-error" class="notice"></span></h4>
        <%= f.text_area :desc, :rows => 2, :class => '', :placeholder => 'Snippet Descrition' %>
      </div>
      <div class="form-code">
        <h4>Code<span id="code-error" class="notice"></span></h4>
        <%= f.text_area :content, :rows => 15, :class => '', :placeholder => '// Paste some code here...' %>
      </div>
      <%= f.hidden_field :filetype %>
      <% if user_signed_in? %>
        <%= f.hidden_field :user_id, :value => current_user.id %>
      <% else %>
        <%= f.hidden_field :user_id %>
      <% end %>
      <div class="form-action clearfix">
      <% if f.object.new_record? %>
        <%= f.submit 'Create Snippet', :class => 'btn btn-info', :id => 'submit-btn' %>
        <a href="<%= snippets_path %>" title="View all snippets" class="view-all pull-right">View all snippets &raquo;</a>
      <% else %>
        <%= f.submit 'Update', :class => 'btn btn-info' %>
        <a href="<%= snippet_path %>" title="Go back" class="view-all pull-right">Go back &raquo;</a>
      <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/snippets/edit.html.erb
<% provide :title, 'Edit Snippet' %>
<% provide :jsfile, 'snippet.form' %>
<%= render 'form' %>

app/views/snippets/index.html.erb
<% provide :title, 'All Snippets' %>

<div class="snippet-list content">
  <div class="content-box">
    <ol>
      <% @snippets.each do |snippet| %>
      <li class="snippet">
        <div class="snippet-info">
          <%= link_to "#{snippet.name}", snippet, class: 'snippet-name', title: 'Show this snippet' %>
          <span class="snippet-author">&raquo; Created by
            <strong><% if snippet.user %><%= snippet.user.name %><% else %>Guest<% end %></strong>
          </span>
          <span class="snippet-type label pull-right"><%= @typenames[snippet.filetype] %></span>
        </div>
        <div class="snippet-desc">
          <strong>Description</strong>: <%= snippet.desc %>
        </div>
      </li>
      <% end %>
    </ol>
  </div>
</div>

app/views/snippets/new.html.erb
<% provide :jsfile, 'snippet.form' %>
<%= render 'form' %>

app/views/snippets/show.html.erb
<% provide :title, "Snippet ##{@snippet.id}" %>
<% provide :jsfile, 'snippet.show' %>

<div class="snippet-box content">
  <div class="alert alert-success clearfix">
    <div class="snippet-name">
      <strong><%= @snippet.name %></strong>
    </div>
    <div class="snippet-author">
      Created by <strong>
        <% if @snippet.user %><%= @snippet.user.name %><% else %>Guest<% end %>
      </strong>
    </div>
  </div>
  <div class="box-body content-box">
    <div class="snippet-desc"><strong>Description: </strong><%= @snippet.desc %></div>
    <div class="snippet-legend">
      <p>Blue line number ( <span style="background-color:#3A87AD;color:#FFF;padding:2px 10px;">N.</span> ) means there are some comments on this line.</p>
      <p>Click on a line to see the comments and to add your comments on this line.</p>
    </div>
    <div id="codebox" class="snippet-code">
      <span class="label label-inverse"><%= @typenames[@snippet.filetype] %></span>
      <% if @typenames[@snippet.filetype].empty? %>
<pre class="prettyprint linenums c-off"><code><%= @snippet.content %></code></pre>
      <% else %>
<pre class="prettyprint linenums c-on"><code class="language-<%= @typenames[@snippet.filetype] %>"><%= @snippet.content %></code></pre>
      <% end %>
<script>prettyPrint();</script>

      <!-- comment popover -->
      <div id="comment-popover" class="comments popover right">
        <div class="arrow"></div>
        <h3 class="popover-title">Comments<button type="button" id="close-cmt" class="close">×</button></h3>
        <div class="popover-content">
          <div class="comments-inner"><ol></ol></div>
          <div class="comment-form">
            <p id="comment-tip" style="display: none"></p>
            <% if not user_signed_in? %>
              <p class="alert">You need to log in before adding a comment.</p>
            <% else %>
              <div class="comment-head pull-left">
                <img src="http://gravatar.com/avatar/<%= current_user.avatar %>?s=32" alt="">
              </div>
              <div class="comment-body">
                <textarea id="comment-input" placeholder="Add some comments..." rows="2"></textarea>
                <input id="comment-userid" type="hidden" value="<%= current_user.id %>">
              </div>
              <div class="comment-action">
                <span id="comment-error" class="notice"></span>
                <a href="#" id="cancel-cmt" class="btn">Cancel</a>&nbsp;&nbsp;
                <a href="#" id="submit-cmt" class="btn btn-info">Submit</a>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <% if user_signed_in? and @snippet.user and current_user.id == @snippet.user.id %>
    <div class="snippet-actions">
      <%= link_to 'Edit', edit_snippet_path(@snippet), class: 'snippet-edit btn' %>
      <%= link_to 'Delete', @snippet, id: 'delete-snippet', class: 'snippet-delete btn btn-danger' %>
    </div>
    <% end %>
  </div>
</div>

<script>
gEarlGreyData = {
  snippetID: <%= @snippet.id %>,
  CMT_GET: '<%= snippet_comments_path @snippet %>.json',
  CMT_CREATE: '<%= snippet_comments_path @snippet %>.json',
  CMT_DELETE: '<%= snippet_path @snippet %>',
};
</script>